### ISSUE TITLE
Fixing package.json to run Storyshots with Svelte

### ISSUE THREAD

**Issue by etsiaDigital** [chromaui/intro-storybook-svelte-template#2]
I wasn't able to successfully run Storyshots as per the tutorial without the following.  Seems like these should be in this template.

The tutorial that I followed is here:  
https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/simple-component/

Your existing template package.json just needs a couple of additions to enable successfully running Storyshot tests:

- add the following to jest
`"transformIgnorePatterns": ["node_modules/(?!(@storybook/svelte)/)"],
`
- add the following to jest  "transform" 
`"^.+\\.stories\\.[jt]sx?$": "<rootDir>node_modules/@storybook/addon-storyshots/injectFileName",
`

Seems like this won't hurt anything with the above and then using Storyshots automatic tests is easy.
If you want to support it completely, add Storyshots to your devDependencies... but if you do that, update to latest versions (you're at Storybook 6.1 and 6.2 is needed for Svelte).  
`"@storybook/addon-storyshots": "^6.2.2",
`

Here's the complete Storybook 6.2 package.json that is working for me:
```{
  "name": "intro-storybook-svelte-template",
  "version": "1.0.0",
  "description": "Starter template to get up and running quickly with Svelte and Storybook",
  "private": true,
  "author": "Chromatic <https://chromatic.com/>",
  "repository": {
    "type": "git",
    "url": "https://github.com/chromaui/intro-storybook-svelte-template"
  },
  "bugs": {
    "url": "https://github.com/chromaui/intro-storybook-svelte-template/issues"
  },
  "license": "MIT",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public",
    "test": "jest --watchAll",
    "storybook": "start-storybook -p 6006 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@rollup/plugin-commonjs": "^16.0.0",
    "@rollup/plugin-node-resolve": "^10.0.0",
    "@storybook/addon-actions": "^6.2.1",
    "@storybook/addon-essentials": "^6.2.1",
    "@storybook/addon-links": "^6.2.1",
    "@storybook/addon-storyshots": "^6.2.2",
    "@storybook/svelte": "^6.2.1",
    "@testing-library/jest-dom": "^5.11.8",
    "@testing-library/svelte": "^3.0.3",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "jest": "^26.6.3",
    "jest-transform-svelte": "^2.1.1",
    "rollup": "^2.3.4",
    "rollup-plugin-copy-assets": "^2.0.3",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.31.2",
    "svelte-loader": "^2.13.6"
  },
  "dependencies": {
    "sirv-cli": "^1.0.0"
  },
  "jest": {
    "transformIgnorePatterns": ["node_modules/(?!(@storybook/svelte)/)"],
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.stories\\.[jt]sx?$": "<rootDir>node_modules/@storybook/addon-storyshots/injectFileName",
      "^.+\\.svelte$": "jest-transform-svelte"
    },
    "moduleFileExtensions": [
      "js",
      "svelte",
      "json"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|scss|stylesheet)$": "<rootDir>/__mocks__/styleMock.js"
    },
    "setupFilesAfterEnv": [
      "@testing-library/jest-dom/extend-expect"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/build/",
      "/storybook-static/"
    ]
  }
}
```

**Comment by jonniebigodes** [comment]
@etsiaDigital thank you for bringing this to our attention, I'm going to update the Svelte version of the tutorial sometime in the next weeks. And I'll factor in your issue when the documentation is updated. To give you a bit more context, this is not an issue with the template itself. Its main job it's only to get you set up with the least amount of commands possible. 

It seems that what the tutorial is missing is the `transformIgnorePatterns` instruction. It might be related to some recent changes introduced.

Stay safe

**Comment by etsiaDigital** [comment]
@jonniebigodes

I saw something different just yesterday or so when creating a "recipe" for myself to start using Storybook more.
Yes originally I had to add the  transformIgnorePatterns but not this second time.  I went back through the tutorial from scratch and I'm capturing the scripts for adding features intelligently to a new project...  I was able to actually run this time with no errors but not 100% as expected.  Here are the issues I see (related to Storyshots/Jest):

- With both Sample.test.js and storybook.test.js w/Storyshots enabled: 
There's a syntax error: 
> Unexpected error while loading ./stories/Introduction.stories.mdx: SyntaxError: Cannot use import statement outside a module
>    at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73) 

There's a `<Button>` warning:
> console.warn
>      `<Button>` was created without expected prop 'backgroundColor'
>      at new Button (src/stories/Button.svelte:162:12)
>      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/svelte/renderTree.js:23:5)

And then there's this variant in behavior depending on Sample.test.js being present or not.  


Here is the behavior **with** Sample.test.js present:
![Screen Shot 2021-04-13 at 4 46 12 PM](https://user-images.githubusercontent.com/56901847/114625887-88333d00-9c78-11eb-8ca8-9a67b16d26db.png)
![Screen Shot 2021-04-13 at 4 47 02 PM](https://user-images.githubusercontent.com/56901847/114625996-b6188180-9c78-11eb-914e-0317dd939396.png)
![Screen Shot 2021-04-13 at 4 47 31 PM](https://user-images.githubusercontent.com/56901847/114626014-bca6f900-9c78-11eb-8ced-7132e9b4dd16.png)

Here is the behavior with Sample.test.js **absent** (and just Storyshots and storybook.test.js as in the tutorial):

Note the deprecation warning as well...
> (node:9928) DeprecationWarning: \`storyFn\` is deprecated and will be removed in Storybook 7.0.
> https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-storyfn
> (Use `node --trace-deprecation ...` to show where the warning was created)

![Screen Shot 2021-04-13 at 5 07 08 PM](https://user-images.githubusercontent.com/56901847/114627346-bb76cb80-9c7a-11eb-99e8-db90b9acb8a8.png)

**Comment by jonniebigodes** [comment]
@etsiaDigital I've gone through the issue you pointed out. And it seems that it's a mismatch of versions. I tested it with the current state of the repo and I was able to check that it indeed leads to that issue. After bumping the package versions to the latest Storybook version (see #3) and running through the tutorial I get this once I reach the Snapshot testing section of that chapter.

![intro-storybook-svelte-initial-snapshots-updated](https://user-images.githubusercontent.com/22988955/115928075-77a37380-a47d-11eb-9ed3-3140e6673228.png)

The deprecation warning is going to follow us to 7.0 at least. I need to check with the current maintainer of Svelte version of Storybook and see what might be the issue there.

I followed the rest of the tutorial to the screen section and ran the command to generate and update the snapshots...As technically that chapter marks the end of the component development and test the results and I got this:

![intro-storybook-svelte-snapshots-screen-section-updated](https://user-images.githubusercontent.com/22988955/115928454-057f5e80-a47e-11eb-8556-73901f0e13d6.png)

I'm currently doing some updates on the tutorial itself and plan on merging the pull request I've mentioned above today (Friday). What I would like from you if you're ok with it is to run the tutorial once more with the updated dependencies and see if the issue still persists and let me know.

Also one thing that sparked my interest in your screenshots, it seems that the addon it's trying to snapshot the mdx files when it shouldn't. Technically it should only capture snapshots for your own stories and not the example ones provided inside the `stories` folder. With that in mind, I would also like to ask you the following, did you update the path in `.storybook/main.js` as mentioned in the Simple Component chapter, under the Config section?

Stay safe

**Comment by etsiaDigital** [comment]
OK @jonniebigodes, 

I'm rerunning from scratch starting here:
   https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/get-started/

When I run 'yarn storybook',  I get the suggestion to upgrade storybook so I do that.
I upgraded as suggested from SB 6.2.8 to 6.2.9 (npx sb@latest upgrade).

Hmmm. I've had to run this a couple of times to figure out what is wrong here when changing .storybook/main.js

Here what you start with and what is in the Tutorial:
- Here's the original .storybook/main.js

![Screen Shot 2021-04-26 at 2 34 43 PM](https://user-images.githubusercontent.com/56901847/116140225-a3e90b00-a69c-11eb-93ae-8f32b7e49b38.png)

- Here's the Tutorial Config section

> 
> ![Screen Shot 2021-04-26 at 2 36 37 PM](https://user-images.githubusercontent.com/56901847/116140353-d7c43080-a69c-11eb-97f8-c108075b913a.png)
> 

- This is what I would recommend using in the tutorial for main.js Config:

![Screen Shot 2021-04-26 at 2 43 01 PM](https://user-images.githubusercontent.com/56901847/116141000-bb74c380-a69d-11eb-8d7a-495f4eef28d4.png)

**And note that there is a typo on the pathname for .storybook/preview.js in the Config pathname above (it has a leading '..').**

I got some odd behavior on my first pass through the tutorial (no stories found) and I'm not sure why.

The next code addition to Task.svelte is wrong (ok misleading).  Here's the tail end of what's currently in Task.svelte:
> 
> ![Screen Shot 2021-04-26 at 2 57 00 PM](https://user-images.githubusercontent.com/56901847/116142751-e7914400-a69f-11eb-8f9c-3569c57bc3bd.png)
> 

And here is the "add this to Task.svelte" in the Tutorial:
> 
> ![Screen Shot 2021-04-26 at 3 00 34 PM](https://user-images.githubusercontent.com/56901847/116143005-30e19380-a6a0-11eb-8076-8f8c744e8ba4.png)
> 

The green + add lines should include that last part of the <script>...  Put a - in front of the old </script> and + green the additional statements.  Personally, drop that + prefix stuff and just use green.  If you want to "delete" a line, make it commented out and green.

That finishes the Task stories and everything works as expected.

I then followed the automated testing instructions.

When I ran "yarn test" it failed:
> 
> ![Screen Shot 2021-04-26 at 3 27 56 PM](https://user-images.githubusercontent.com/56901847/116146456-23c6a380-a6a4-11eb-9998-91fac8395c92.png)
> 

So I added the following to the Jest property in package.json:
` "transformIgnorePatterns": ["node_modules/(?!(@storybook/svelte)/)"],`

It seems I had to re-run 'yarn storybook', and my .storybook/main.js is like this:
> module.exports = {
>   // The following stories: picks up the Examples as well as the 'components'
>   //  stories: ["../src/**/*.stories.js", "../src/components/**/*.stories.js"],
>   // The following will just pick up stories in 'components'
>   stories: ["../src/components/**/*.stories.js"],
>   addons: [
>     "@storybook/addon-actions",
>     "@storybook/addon-links",
>     "@storybook/addon-essentials",
>     "@storybook/addon-storyshots",
>   ],
> };

and THEN I got this result:
> 
> ![Screen Shot 2021-04-26 at 3 39 08 PM](https://user-images.githubusercontent.com/56901847/116147614-92583100-a6a5-11eb-971c-e1495f6ba5da.png)
> 

cheers.

**Comment by etsiaDigital** [comment]
Let me summarize the changes to the Svelte tutorial that would clean up the issues:

1. There needs to be a better path to the Tutorial.  The "Get Started" button on this page:  https://storybook.js.org/tutorials/intro-to-storybook/   should be a drop down allowing framework selection and then route accordingly.  You have to manually do that.

2. On this page: https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/simple-component/  in the **Config** section I would simplify / correct the config files {.storybook/main.js, .storybook/preview.js} to be a cut/paste-able form. They should be:
- .storybook/main.js   (note this is a simple edit of what is there already.. so it will be clear whats going on)
```
module.exports = {
  stories: [
    // NOTE the following used to be "../src/components/**/*.stories.js"  which is wrong
    //   It should be "../src/components/*.stories.js" or
    "../src/**/*.stories.js"],
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-actions",
  ],
};
```

- .storybook/preview.js    (**NOTE** there was a typo here on the web page re: the preview.js path)
```
import "../src/index.css";
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
};
```

3. Same page, **Build out the states** section.  Change the src/components/Task.svelte file contents to be cut/paste-able.  If you wish to highlight the changes, do so with color only.  The delta indicated is wrong because it omits the // reactive declaration addition just above the markup.  That's the svelte part of the <script> change.

4. Same page, **Snapshot testing** section.  Provide a cut/paste-able form of package.json and add the transformIgnorePatterns prop to Jest.  You could highlight the 2 additions in green if you want.

```
  "jest": {
    "transformIgnorePatterns": ["node_modules/(?!(@storybook/svelte)/)"],
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.stories\\.[jt]sx?$": "<rootDir>node_modules/@storybook/addon-storyshots/injectFileName",
      "^.+\\.svelte$": "jest-transform-svelte"
    },

```

5. Same page, **Snapshot testing** section.  You need to add a paragraph after changing the jest key in package.json:

> Rename the file  **src/Sample.test.js**   to   **src/Sample.test.js.orig**


That's it.

**Comment by jonniebigodes** [comment]
@etsiaDigital thanks for the suggestions, I want to go over them so that we're on the same page here and don't accidentally introduce misconceptions:

> There needs to be a better path to the Tutorial. The "Get Started" button on this page: https://storybook.js.org/tutorials/intro-to-storybook/ should be a drop down allowing framework selection and then route accordingly. You have to manually do that.

Regarding this item, if you could open up an issue in the tutorial's repo [here](https://github.com/chromaui/learnstorybook.com), we'd appreciate it and would look into it.

> .storybook/main.js (note this is a simple edit of what is there already.. so it will be clear whats going on)

Regarding this item, I have changed it locally on my end, and when the pull request is merged the pattern is fine-tuned. What's intended here is to focus on the components/stories the reader is working on. The sample stories that are provided with each Storybook installation are a good source of inspiration, but not applicable in terms of the tutorial. In a nutshell, we don't need them.

Also, by introducing the proposed change you've mentioned in your code snippet, we're actually introducing a misconception. The [`"@storybook/addon-storyshots"`](https://storybook.js.org/docs/react/workflows/snapshot-testing)  doesn't need to be referenced in `.storybook/main.js`, it's one of the few ones that are at the lack of a better word independent of Storybook. Its main job is to pull in the stories you've created and run tests based on what you've set up in terms of stories.


> .storybook/preview.js (NOTE there was a typo here on the web page re: the preview.js path)

Regarding this item, it's taken care of. The typo is fixed on changes I'm going to introduce in the tutorial.


> Same page, Build out the states section. Change the src/components/Task.svelte file contents to be cut/paste-able. If you wish to highlight the changes, do so with color only. The delta indicated is wrong because it omits the // reactive declaration addition just above the markup. That's the svelte part of the <script> change.

Regarding this item, it's already adjusted on my end and I'll push it to a pull request shortly. One thing to keep in mind is that the way the website is built (it uses Gatsby) and the way we're demonstrating what changes are required with the code snippets we don't have a way to just pull in some color changes into the snippet. It requires a lot of changes in terms of the plugins that are in play. This is something outside of our control and up to the maintainers of said Gatsby plugins to work on.

Regarding the copy and paste, that's something that I want to work on in the near future and allow you and the rest of the readers a streamlined approach when copying and pasting the code. 

> Same page, Snapshot testing section. Provide a cut/paste-able form of package.json and add the transformIgnorePatterns prop to Jest. You could highlight the 2 additions in green if you want.

Regarding this item, it's already adjusted on my end and will be featured in the pull request I'm going to create shortly.

> Same page, Snapshot testing section. You need to add a paragraph after changing the jest key in package.json:

Regarding this item, at this stage (Composite component), it's irrelevant if the `Sample.test.js` is there or not. The test will go through without errors. The real concern, in this case, is when you or another reader gets to the Screen chapter of the tutorial and decides to run the testing suite. Then, it will break the tests. Based on the feedback I got since this particular version of the tutorial was introduced and now it seems that some readers want the test in, others don't. So to reach a middle ground I've polished the aside on that chapter to instruct the readers to update the test and component based on what was introduced. Leaving up to them.

**Comment by etsiaDigital** [comment]
**Ack**
I just saw what was causing me some flakiness and is a problem:

The `"../src/components/**/*.stories.js"` in .storybook/main.js is wrong.  It has an erroneous extra directory layer.
This should be **"../src/components/*.stories.js"** or just leave it `"../src/**/*.stories.js"` which would then also include the examples in src/stories.

<hr />

- .storybook/main.js  
```
module.exports = {
  stories: [
    // NOTE the following used to be "../src/components/**/*.stories.js"  which is wrong
    //   It should be "../src/components/*.stories.js" or
    "../src/**/*.stories.js"],
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-actions",
  ],
};
```



When you include src/stories, you do get warnings about backgroundColor expected but missing.  The tests all pass:

![Screen Shot 2021-04-27 at 9 24 52 PM](https://user-images.githubusercontent.com/56901847/116337092-3bcf1d80-a79f-11eb-8ff3-29cca64521db.png)
![Screen Shot 2021-04-27 at 9 25 38 PM](https://user-images.githubusercontent.com/56901847/116337142-4ab5d000-a79f-11eb-9d43-a40236bbbbef.png)



Regarding the **transformIgnorePatterns** prop for Jest,  I've had a mixed experience with this.  At some earlier time in testing, I didn't need it.  The last pass, I got errors and needed it.  To be safe, and because it's reasonable in any event (in Svelte's case), I'd keep it in for reliability.


There has to be some inter-dependencies here that a new Storybook user won't have a clue about.  Your **framework specific tutorial templates** I've seen mentioned elsewhere will solve all of that and provide a predictable first experience.


As an aside, I like the broken out story checkmarks with test timing that you see here:

![Screen Shot 2021-04-26 at 3 39 08 PM](https://user-images.githubusercontent.com/56901847/116333865-e17f8e00-a799-11eb-8ea0-74141bbd3ce3.png)

and here:
![Screen Shot 2021-04-13 at 5 07 08 PM](https://user-images.githubusercontent.com/56901847/116334039-2c010a80-a79a-11eb-9878-10292e018f3a.png)

rather than a simple "PASS" of the test file (like src/storybook.test.js) like here:
![Screen Shot 2021-04-27 at 8 57 09 PM](https://user-images.githubusercontent.com/56901847/116338647-b26d1a80-a7a1-11eb-9b2d-0e4f80de0f37.png)

I don't understand why sometimes running "yarn test" produces the itemized storyshot testing w/times vs just the PASS of a test file.

Sorry I missed that pathname problem.

**Comment by jonniebigodes** [comment]
No worries, i'm closing this issue as it's fixed. Stay safe
