### ISSUE TITLE
No longer update to date

### ISSUE THREAD

**Issue by cchantep** [chromaui/intro-storybook-svelte-template#8]
Keep dependencies up to date

**Comment by jonniebigodes** [comment]
@cchantep thanks for taking the time to reach out to us and let us know of the issue. The template was updated to allow you to use it around all modes (development, storybook, testing). I'm aware that this is no longer recommended as Svelte is pushing towards Vite. This template will be updated a bit later on as part of the Storybook 7.0 release as it will give time for the Storybook [Vite builder](https://github.com/storybookjs/builder-vite) to mature a bit more.

**Comment by kakakaya** [comment]
Hello!

I'm new to Storybook. My project is using Svelte, and trying to start using Storybook.  I've found a tutorial to use this project as template, but some steps doesn't work well.
https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/get-started/

My Question: Are the tutorial and this template outdated? 

While I'm writing this comment, I've found newer tutorial for Svelte. Should I use this?
https://storybook.js.org/docs/get-started/svelte-vite

**Comment by jonniebigodes** [comment]
@kakakaya thanks for reaching out with your question. Appreciate it 🙏 ! This template and the tutorial version are a bit outdated. I have the changes almost ready, but I hadn't had the time to get them in as I was tasked with other aspects of the documentation that required my attention. Hopefully, I'll get around to updating them shortly. Sorry for the inconvenience.

Hope you have a great day.

Stay safe

**Comment by kakakaya** [comment]
Thanks for the update! No worries at all about the delay. I totally understand you've had other priorities to handle.

I'm excited to see the improvements whenever you're able to get the changes ready. Looking forward to it!

In the meantime, hope you have a great rest of your week.

Cheers
